name: CI for Multiple Docker Images

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Test Image 
      run: |
        docker build -t lexluga/react-test -f ./client/Dockerfile.dev ./client

    - name: Test Image After Install
      run: |
        docker run -e CI=true lexluga/react-test npm run test -- --coverage


    - name: Build Docker Client
      run: | 
        docker build -t lexluga/multi-client ./client 

    - name: Build Nginx Server
      run: | 
        docker build -t lexluga/multi-nginx ./nginx

    - name: Build API Server
      run: |
        docker build -t lexluga/multi-server ./server

    - name: Build Worker Process
      run: |
        docker build -t lexluga/multi-worker ./worker

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to Docker Hub
      run : | 
        docker push lexluga/multi-client
        docker push lexluga/multi-nginx
        docker push lexluga/multi-server
        docker push lexluga/multi-worker

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
   
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


    