name: CI to Multiple Docker Builds

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Check Out Repo 
      uses: actions/checkout@v2

    # - name: Docker Login
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build Docker Test Image 
      run: |
        docker build -t lexluga/react-test -f ./client/Dockerfile.dev ./client

    - name: Test Image After Install
      run: |
        docker run -e CI=true lexluga/react-test npm run test -- --coverage


    - name: Build Docker Client
      run: | 
        docker build -t lexluga/client:1.0.0 ./client 

    - name: Build Nginx Server
      run: | 
        docker build -t lexluga/nginx:1.0.0 ./nginx

    - name: Build API Server
      run: |
        docker build -t lexluga/server:1.0.0 ./server

    - name: Build Worker Process
      run: |
        docker build -t lexluga/worker:1.0.0 ./worker

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: lexluga/multi-docker:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache 
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


    